### ISSUE TITLE
仅支持php5.6，版本太低了，现在大多数厂商都是php 7.0+

### ISSUE THREAD

**Issue by daichepin** [polarismesh/polaris-php#5]
仅支持php5.6，版本太低了，现在大多数厂商都是php 7.x+，希望官方尽快兼容php7.0+

**Comment by chuntaojun** [comment]
是的，我们会尽快在现有版本基础之上，支持php-7.x的版本

**Comment by chuntaojun** [comment]
https://github.com/polarismesh/polaris-php/issues/4

**Comment by chuntaojun** [comment]
可以看看这个分支：https://github.com/polarismesh/polaris-php/tree/php-7.x

**Comment by Akuns** [comment]
> 可以看看这个分支：https://github.com/polarismesh/polaris-php/tree/php-7.x

好勒

**Comment by chuntaojun** [comment]
https://github.com/polarismesh/polaris-php/releases

**Comment by chuntaojun** [comment]
这里是php5.x以及php7.x的beta版本插件包

**Comment by Akuns** [comment]
> 这里是php5.x以及php7.x的beta版本插件包

好的
